#!/bin/bash

MODE=$(tlp-stat -s | grep Mode | awk '{print $3}')

toggle() {
    if [[ $MODE == 'battery' ]]; then
        pkexec tlp ac
        notify-send --urgency=normal "Power Saver" "Power saving mode has been turned off!" -i power-profile-balanced-symbolic
    else
        pkexec tlp bat
        notify-send --urgency=normal "Power Saver" "Power saving mode has been turned on!" -i power-profile-power-saver-symbolic
    fi
}

status() {
    if [[ $MODE == 'battery' ]]; then
        echo "On"
    else
        echo "Off"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--mode" ]]; then
    echo $MODE
elif [[ $1 == "--status" ]]; then
    status
fi
