# Layout (reduced/original/mid)
layout=reduced

# Appearance
boxalpha=140
seekbarfg_color="00CED1"
seekrange=yes
seekrangealpha=100

# Behavior
showonpause=yes
timetotal=no
timems=no
visibility=auto
hidetimeout=2000
fadeduration=150
deadzone=150

# Controls
volumecontrol=yes
windowcontrols=auto
scalewindowed=1
scalefullscreen=1
language=eng

# Scale
vidscale=no
