# Disable native OSC (using modernf)
osc=no

# Window
border=no
autofit=1280x720
geometry=50%

# Playback
cache=yes
cache-default=75000
demuxer-max-bytes=150M
force-window=immediate
idle=active

# Audio
audio-file-auto=no

# Subtitle
sub-auto=fuzzy
sub-codepage=utf8

# OSD
osd-font='Inter'
osd-font-size=28
osd-color='#CCFFFFFF'
osd-border-color='#66000000'
osd-shadow-color='#66000000'

# Screenshots
screenshot-directory="~/Pictures/Screenshots"
screenshot-template="%F_%p"
