[env]
TERM = "xterm-256color"

[font]
size = 10 

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold]
family = "Monaspace Neon"
style = "ExtraBold"

[font.bold_italic]
family = "Monaspace Neon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Neon"
style = "Italic"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[window]
opacity = 0.65
#opacity = 1

[window.padding]
x = 15
y = 15

[general]
ipc_socket = true

import = [
   #"~/.config/alacritty/catppuccin-mocha.toml"
   #"~/.config/alacritty/gruvbox_material_hard_dark.toml"
   #"~/.config/alacritty/monokai.toml"
   #"~/.config/alacritty/rose-pine.toml"
   "colors.toml"
   # "~/.config/alacritty/cosmicmidnight.toml"
]
