# Global settings
format = """\
[╭╴](fg:arrow)\
$username\
$directory\
$time\
(\
    $git_branch\
    $git_status\
)\
(\
    $python\
    $conda\
    $nodejs\
)\
$cmd_duration
[╰─](fg:arrow)$character\
"""
add_newline = true
palette = "matugen"

# Palette definition
[palettes.matugen]
arrow = "{{colors.on_surface.default.hex}}"
os = "{{colors.primary.default.hex | set_lightness: -15.0}}"
os_admin = "{{colors.error.default.hex}}"
directory = "{{colors.secondary.default.hex | set_lightness: -15.0}}"
node = "{{colors.tertiary.default.hex}}"
time = "{{colors.surface_bright.default.hex}}"
git = "{{colors.primary_container.default.hex}}"
git_status = "{{colors.secondary_container.default.hex}}"
python = "{{colors.tertiary_container.default.hex}}"
conda = "{{colors.primary.default.hex}}"
java = "{{colors.error.default.hex}}"
rust = "{{colors.tertiary.default.hex}}"
clang = "{{colors.secondary.default.hex}}"
duration = "{{colors.tertiary.default.hex}}"
text_color = "{{colors.on_primary_container.default.hex | set_lightness: +10.0}}"
text_light = "{{colors.on_secondary_container.default.hex}}"

# Module definitions
[username]
style_user = 'os'
style_root = 'os_admin'
format = '[]($style)[ Emin](bg:$style fg:text_color)[]($style)'
disabled = false
show_always = true

[character]
success_symbol = "[󰍟](fg:arrow)"
error_symbol = "[󰍟](fg:red)"

[directory]
format = " [](fg:directory)[  $path ]($style)[$read_only]($read_only_style)[](fg:directory)"
truncation_length = 2
style = "fg:text_color bg:directory"
read_only_style = "fg:text_color bg:directory"
before_repo_root_style = "fg:text_color bg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only ="  "

[time]
disabled = false
format = " [](fg:time)[ $time]($style)[](fg:time)"
time_format = "%H:%M"
style = "fg:text_color bg:time"

[cmd_duration]
format = " [](fg:duration)[ $duration]($style)[](fg:duration)"
style = "fg:text_light bg:duration"
min_time = 500

[git_branch]
format = " [](fg:git)[$symbol$branch](fg:text_light bg:git)[](fg:git)"
symbol = " "

[git_status]
format = '([ ](fg:git_status)[ $all_status$ahead_behind ]($style)[](fg:git_status))'
style = "fg:text_light bg:git_status"

[docker_context]
disabled=true
symbol = " "

[package]
disabled=true

[java]
format = "[ ](fg:java)[$symbol$version](bg:java fg:text_color)[](fg:java)"
version_format = "${raw}"
symbol = " "
disabled = true

[nodejs]
format = "[ ](fg:node)[$symbol$version]($style)[](fg:node)"
style = "bg:node fg:text_light"
symbol = " "
version_format = "${raw}"
disabled=false

[rust]
format = "[ ](fg:rust)[$symbol$version](bg:rust fg:text_color)[](fg:rust)"
symbol = " "
version_format = "${raw}"
disabled=true

[python]
disabled=false
format = '[ ](fg:python)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[](fg:python)'
symbol = " "
version_format = "${raw}"
style = "fg:text_light bg:python"

[conda]
format = "[ ](fg:conda)[$symbol$environment]($style)[](fg:conda)"
style = "bg:conda fg:text_color"
ignore_base = false
disabled=false
symbol = " "

[c]
format = "[ ](fg:clang)[$symbol($version(-$name) )](bg:clang fg:text_color)[](fg:clang)"
symbol = " "
version_format = "${raw}"
disabled=true

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "