#################################
#            Startup            #
#################################
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec thunar --daemon &
exec systemctl start --user app-com.mitchellh.ghostty.service
#exec_always ~/.config/sway/script.d/screensetup.sh
exec swayosd-server &
exec /usr/bin/swayidle -w timeout 840 "gtklock" timeout 900 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' &
exec swaync
exec ags & # Widgets
exec nm-applet
exec /usr/bin/kdeconnectd &
exec autotiling-rs &
exec flameshot &

#exec /usr/bin/swayidle -w timeout 240 "~/.config/sway/script.d/powermenu.sh --lock" timeout 500 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' &
# exec_always zsh ~/.config/i3/eww.sh &
# exec zsh -c "~/.config/eww/scripts/logger.py init &"
# exec ~/.config/eww/scripts/bin/python ~/.config/eww/scripts/logger.py init &
# exec dunst &
