# =============================================================================
# SHARED LAYER RULES
# =============================================================================

layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = blur on, match:namespace waybar
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-notification-window
layerrule = blur on, ignore_alpha 0, match:namespace swayosd-client
layerrule = blur on, ignore_alpha 0, match:namespace swayosd-server
layerrule = blur on, ignore_alpha 0, xray 0, match:namespace swayosd
layerrule = blur on, ignore_alpha 0, match:namespace vicinae

# =============================================================================
# SHARED WINDOW RULES
# =============================================================================

windowrule = no_initial_focus on, no_focus on, match:class "swaync-notification-window"
windowrule = no_screen_share on, match:title (Telegram)(.*)
windowrule = no_screen_share on, match:title (WhatsApp)(.*)
windowrule = no_screen_share on, match:title (.*)(All mail)(.*)
windowrule = no_screen_share on, match:title (.*)(Inbox \| .* \| Proton Mail)(.*)
windowrule = float on, match:class ^(gradia)$
windowrule = float on, center on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(nwg-look|wdisplays|qt6ct|qt5ct|kvantummanager)$
windowrule = float on, match:class ^(easyeffects)$
windowrule = float on, match:class ^(org.kde.ark|file-roller)$
windowrule = immediate on, match:class ^(cs2)$
windowrule = float on, match:class ^(com.sessionizer.fzf)$
windowrule = size 800 500, match:class ^(com.sessionizer.fzf)$
windowrule = center on, match:class ^(com.sessionizer.fzf)$
